### PR TITLE
Extend the Kernel module with the #retryable method

### PR DESCRIPTION
**Pull request by kamui**
I'm not sure if you would be interested in my fork, but I'm sending you this pull request anyway.

I moved #retryable into the Kernel module so that you can use it as if it were a built in construct in Ruby. I feel like the capability it provides would be better suited without having to include it in your classes or having to call it with the Retryable namespace.

I also updated the gemspec, added a Gemfile and updated your Raketask file to what's generated from Bundler these days. I made sure all the tests pass and updated the README and CHANGELOG. I bumped the version to 1.2.0 too so you can release a new gem if you wanted to.

I renamed the lib/retryable.rb to lib/retryable-rb.rb and renamed references from Retryable to RetryableRB, because there's already a retryable gem and this name change allows you to do:

gem 'retryable-rb' # in your Gemfile without needing to add :require => 'retryable'

Thanks for a useful gem.

### CODE REVIEW

**Comment by bartoszrega** [comment]
+1

**Comment by wintery** [comment]
+1

**Comment by tmilewski** [comment]
+1

**Comment by kamui** [comment]
I'm going to close this ticket since I've decided to fork it and play around with the code as my own gem.

**Comment by phiggins** [comment]
Why not add a new file, for example, 'retryable/core_ext' that looks something like:

```
Kernel.send(:include, Retryable)
Kernel.send(:extend, Retryable)
```

That way, if you want it mixed in everywhere, you can require the core_ext file, and if not you do it the old way.

**Comment by kamui** [comment]
``` ruby
Kernel.send(:include, Retryable)
```

This doess't quite work in some cases. main Object in IRB for example won't see this unless you re-include Kernel in the Object class.

That said, I'm going to do something like this, but since I want #retriable in Kernel, I'm going to make that the default. Then if you want the non kernel version you can just do something like this in your Gemfile:

``` ruby
gem 'retriable', require => 'retriable/no_kernel'
```

**Pull request closed without merging**
